model:
  d_model: 512
  modalities: 
    esm2: '/data/PHURI-Langenberg/people/Nat/Protein-Prediction/Configs/extractors/esm-C.yaml'
  fusion: '/data/PHURI-Langenberg/people/Nat/Protein-Prediction/Configs/fusion_layers/concatenation.yaml'
  mlp: '/data/PHURI-Langenberg/people/Nat/Protein-Prediction/Configs/classifiers/SimpleMLP.yaml'

training:
  epochs: 200
  batch_size: 32
  patience: 20
  
paths:
  embedding_dir: 'Data/Embeddings/'
  labels_path: 'Data/Labels/labels.pt'
  checkpoint_dir: 'Logs/Checkpoints/'
  raw_csv: '/data/PHURI-Langenberg/people/Nat/Protein-Prediction/Data/NN_input/true_positives_and_true_negatives.csv'

uni_prot:
  backoff_factor: 0.5
  retries: 3